# Generated by Django 5.2.5 on 2025-09-01 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tariff',
            field=models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tariff'], name='core_applic_tariff_a48b7a_idx'),
        ),
    ]
